Feature/beneficiarios
TechNix-Company/Isabel pull request #59
Opened 2020-11-16 21:41 UTC by Valeriagdlo99

CRUD completo de beneficiarios
Registrar, consultar, eliminar, el listado, etc.

2020-11-18 01:33 UTC, PValenciac commented on beneficiarios_detalle.php
> +                        if (isset($_POST['pernoctan'])==true) {
Detalle menor: no es necesario hacer `==true`, **isset** te va a regresar true|false.

2020-11-18 01:34 UTC, PValenciac commented on beneficiarios_detalle.php
> +                                var_dump($beneficiario_id ,$nombre, $fecha, $genero, $pernoctan );
Creo que hay que borrar este var_dump.

2020-11-18 01:42 UTC, PValenciac requested changes
Se ve bastante bien, vale. Dejé un par de comentarios.

2020-11-18 01:42 UTC, PValenciac commented on beneficiarios_detalle.php
> +                                var_dump($beneficiario_id ,$nombre, $fecha, $genero, $pernoctan );
Creo que hay que borrar este var_dump.

2020-11-18 01:42 UTC, PValenciac commented on migrations/migration-05.sql
> +    nombre VARCHAR(50) NOT NULL,
Creo que 50 caracteres puede ser muy poco. En mi opinión, 124 quedaría un poco mejor solo para estar seguros.

2020-11-18 01:42 UTC, PValenciac commented on statics/partial_templates/beneficiarios/_admin_beneficiario_detalle.html
> +            <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingresa el nombre del benericiario"   required  <?php if($_GET["accion"] == 'consultar'   ): ?> disabled  <?
Te recomiendo utilizar los atributos minlentgh y maxlength para hacer validaciones.

2020-11-18 01:42 UTC, PValenciac commented on statics/partial_templates/beneficiarios/_beneficiarios.html
> +    <?php endif ?>
Creo que el  `<?php endif ?>` debería estar una tag arriba. No estoy muy seguro.

2020-11-19 03:21 UTC, PValenciac approved these changes

2020-11-19 06:30 UTC, GlinkIsCoding approved these changes

2020-11-19 06:30 UTC, merged