Corregir tarjetas de listado de proyectos
TechNix-Company/Isabel pull request #64
Opened 2020-11-18 17:16 UTC by Adolfo-A01705249

Se agrego una nueva clase de css para darle a las imagenes
de las tarjetas en el listado de proyectos la misma regla
que a las imagenes de las tarjetas de eventos.

Se uso la misma regla en las tarjetas de eventos para evitar
usar el atributo style dentro del codigo .html

2020-11-18 21:46 UTC, PValenciac commented on statics/custom-styles.css
> +
Es buena idea ponerle un height específico a los componentes para evitar problemas con los textos.

2020-11-18 21:46 UTC, PValenciac approved these changes

2020-11-19 01:59 UTC, Valeriagdlo99 requested changes
Perfecto!

2020-11-19 01:59 UTC, Valeriagdlo99 approved these changes

2020-11-19 02:00 UTC, merged